### PR TITLE
DON'T Merge Feature/AxonFramework (use #123, #124, #125)

### PR DESCRIPTION
**Pull request by zambrovski**
Hi Oliver,

here is a PR implementing the Axon Framework support. I would be happy for any feedback on this, since I believe this feature is very valuable (for all Axon users).

**Current**
- Updated pom.xml with to use latest Maven Plugins, set enforced JDK to 17 (is LTS), add dependencies to Axon Framework
- Add more helpers to `PluginSupport` and `JMoleculesElementMatchers`
- Implemented `AxonFramework` and `Axon Spring` bytebuddy plugins
- Added an example with an Axon Test (as a separate project) to test that the annotation really work

**Temporary**
- Added "local" `Association` annotation until 1.6 containing is released

**TODO / Missing**:
- Docs for usage are missing
- Convince you to add support for Query model https://github.com/xmolecules/jmolecules/issues/87

**Fixes**:
https://github.com/xmolecules/jmolecules-integrations/issues/121

Cheers,

Simon

### CODE REVIEW

**Comment by odrotbohm** [comment]
This looks very well already! Would you mind applying the formatting settings you find [here](https://github.com/spring-projects/spring-data-build/tree/main/etc/ide) to the PR? It looks like the changeset contains a lot of formatting changes and result in a wild mixture of tabs and spaces.

Does Axon require Java 17 already? As we would like to stay compatible with Boot 2.x, we need to generally be Java 8 compatible with the source code we produce. If the Axon JARs already require Java 17, we, of course, can upgrade the build script to make sure it uses a JDK 17 to build.

**Comment by zambrovski** [comment]
Sorry for bad formatting, will apply this.

Java 17 - no for axon it is just fine to run on JDK 8+. In jmolecules-integrations parent pom you had an enforcer plugin forcing me to have exactly JDK 15 (which I don't have on my machine), so I decided not to remove it entirely, but to upgrade to latest LTS (17). It is up to you what to use, usually I enforce to use 11+ - the previous LTS and most popular as far as I can see from other projects I'm in...

**Comment by odrotbohm** [comment]
Hm, there are still quite a few sole formatting changes that clutter the diff. I'd also like to clearly separate changes that are nice but actually unrelated to the actual functionality (updating the Maven compiler plugin version or the use of .jenv) from the *actual* changes. I'd even argue, they shouldn't be in this PR at all.

The example project could use Lombok to avoid a lot of boilerplate needing to be read and understood.

I like the idea of centralizing the filtering of platform types (Java, Kotlin etc.). I'd even go ahead and make that a dedicated method to avoid having to expose the list of values. Right now it's only handed into a method on the very same type that exposes the list in the first place. That feels like unnecessary ceremony.

I don't want to drag this out for you as the core parts of the contribution are very valuable and I don't want to waste your time. If you'd like, I just can take it from here and polish stuff up as we need it.

**Comment by zambrovski** [comment]
Tell me how I can help. So I can separate the request in several.

My approach of grouping would be:

- maven stuff
- pre-formatting of existing code to be changed without any further changes
- adding new code 


What do you think?

Cheers,

Simon

**Comment by odrotbohm** [comment]
Sounds good to me! And thanks again for your patience! 🙃

**Comment by zambrovski** [comment]
Instead of PR #120 I created #122, #123 and #124 ...
I think it is easier now to understand the changes.

I hope this way we get it done soon.


Btw. have you seen the issues I opened in xmolecules/jmolecules? The https://github.com/xmolecules/jmolecules/issues/83 and https://github.com/xmolecules/jmolecules/issues/84 are trivial (more like bugs), but the issue about the query is more a conceptional question.

**Pull request closed without merging**
